#!/bin/sh
# embed_assets.sh - Shell script alternative to embed_assets.py
# Generates C++ header with embedded web assets using only basic shell tools
# Usage: embed_assets.sh <web_dir> <output_header>
# Requires: basically just sed

set -e

if [ $# -ne 2 ]; then
    echo "Usage: $0 <web_dir> <output_header>" >&2
    exit 1
fi

WEB_DIR="$1"
OUTPUT_FILE="$2"

HTML_FILE="${WEB_DIR}/index.html"
CSS_FILE="${WEB_DIR}/style.css"
JS_FILE="${WEB_DIR}/app.js"

# Check if input files exist
if [ ! -f "$HTML_FILE" ]; then
    echo "Error: $HTML_FILE not found" >&2
    exit 1
fi
if [ ! -f "$CSS_FILE" ]; then
    echo "Error: $CSS_FILE not found" >&2
    exit 1
fi
if [ ! -f "$JS_FILE" ]; then
    echo "Error: $JS_FILE not found" >&2
    exit 1
fi

# Create temporary file for processing HTML
TEMP_HTML=$(mktemp)
trap "rm -f '$TEMP_HTML'" EXIT

sed '/<style>\/\* INJECT_CSS \*\/<\/style>/ {
    s|<style>.*</style>|<style>|
    r '"$CSS_FILE"'
    a </style>
}' "$HTML_FILE" | \
sed '/<script>\/\* INJECT_JS \*\/<\/script>/ {
    s|<script>.*</script>|<script>|
    r '"$JS_FILE"'
    a </script>
}' > "$TEMP_HTML"

# Generate the C++ header file
cat > "$OUTPUT_FILE" << 'EOF_HEADER'
// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by embed_assets.sh during build
// Contains embedded web assets for tr-web plugin

#ifndef TR_WEB_ASSETS_H
#define TR_WEB_ASSETS_H

namespace tr_web {

static const char* HTML_PAGE = R"TR_WEB_DELIM(
EOF_HEADER

# Append the HTML content
cat "$TEMP_HTML" >> "$OUTPUT_FILE"

# Append the closing
cat >> "$OUTPUT_FILE" << 'EOF_FOOTER'
)TR_WEB_DELIM";

} // namespace tr_web

#endif // TR_WEB_ASSETS_H
EOF_FOOTER

echo "Generated $OUTPUT_FILE" >&2
