#!/usr/bin/env python3
# embed_assets.py - Generates C++ header with embedded web assets
# Run by CMake during build to embed HTML, CSS, and JS files

import sys
import os

def escape_for_cpp(content):
    """Escape content for C++ raw string literal"""
    return content

def read_file(filepath):
    """Read file content"""
    with open(filepath, 'r', encoding='utf-8') as f:
        return f.read()

def generate_header(web_dir, output_file):
    """Generate C++ header with embedded assets"""
    
    html_path = os.path.join(web_dir, 'index.html')
    css_path = os.path.join(web_dir, 'style.css')
    js_path = os.path.join(web_dir, 'app.js')
    
    html_content = read_file(html_path)
    css_content = read_file(css_path)
    js_content = read_file(js_path)
    
    # Inject CSS and JS into HTML
    html_content = html_content.replace('/* INJECT_CSS */', css_content)
    html_content = html_content.replace('/* INJECT_JS */', js_content)
    
    # Generate header
    header = '''// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by embed_assets.py during build
// Contains embedded web assets for tr-web plugin

#ifndef TR_WEB_ASSETS_H
#define TR_WEB_ASSETS_H

namespace tr_web {

static const char* HTML_PAGE = R"TR_WEB_DELIM(
''' + html_content + '''
)TR_WEB_DELIM";

} // namespace tr_web

#endif // TR_WEB_ASSETS_H
'''
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(header)
    
    print(f"Generated {output_file}")

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <web_dir> <output_header>")
        sys.exit(1)
    
    generate_header(sys.argv[1], sys.argv[2])
